import { Language } from "../types/i18n";

export const TERMS_OF_SERVICE_TEXT: Record<Language, string> = {
  en: `Terms of Service and Disclaimer
Last updated: November 28, 2025

[AlphaGo] ("the App") is an educational and entertainment tool designed to assist users in identifying consumable products via photograph analysis powered by artificial intelligence.

1. No Guarantee of Accuracy
The identifications provided by the App are generated by artificial intelligence and third-party APIs. These identifications are NOT 100% accurate and are provided for informational and educational purposes only. The App is NOT a substitute for professional botanical, mycological, medical, or foraging expertise.

2. Assumption of Risk
You expressly acknowledge and agree that any use of the information provided by the App, including but not limited to any consumable product or other natural substance identified by the App, is done entirely at your own risk.

3. No Liability for Harm
In no event shall the developers, owners, affiliates, licensors, or any related parties of [AlphaGo] be liable for any injury, illness, allergic reaction, poisoning, death, property damage, or any other harm whatsoever arising from or related to the use of this App, including but not limited to the consumption or handling of any substance identified (correctly or incorrectly) by the App.

4. Indemnification
You agree to indemnify, defend, and hold harmless the developers and owners of the App from any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of your use of the App or your consumption or handling of any substance identified by the App.

5. Not Medical or Professional Advice
The App does not provide medical, nutritional advice. Always consult qualified experts before consuming wild plants, mushrooms, or any foraged items.

6. Age Requirement
By using this App you represent that you are at least 18 years of age or are using the App under the supervision of a parent or legal guardian who agrees to these Terms.

7. Acceptance
By checking the box and tapping "Continue", you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and Disclaimer.

If you do not agree, you must tap "Decline" and uninstall the application.`,
  es: `Términos de Servicio y Descargo de Responsabilidad
Última actualización: 28 de noviembre de 2025

[AlphaGo] ("la Aplicación") es una herramienta educativa y de entretenimiento diseñada para ayudar a los usuarios a identificar productos consumibles a través del análisis fotográfico impulsado por inteligencia artificial.

1. Sin Garantía de Precisión
Las identificaciones proporcionadas por la Aplicación son generadas por inteligencia artificial y APIs de terceros. Estas identificaciones NO son 100% precisas y se proporcionan únicamente con fines informativos y educativos. La Aplicación NO es un sustituto de experiencia profesional botánica, micológica, médica o de recolección.

2. Asunción de Riesgo
Usted reconoce y acepta expresamente que cualquier uso de la información proporcionada por la Aplicación, incluido pero no limitado a cualquier producto consumible u otra sustancia natural identificada por la Aplicación, se realiza enteramente bajo su propio riesgo.

3. Sin Responsabilidad por Daños
En ningún caso los desarrolladores, propietarios, afiliados, licenciantes o cualquier parte relacionada de [AlphaGo] serán responsables de cualquier lesión, enfermedad, reacción alérgica, envenenamiento, muerte, daño a la propiedad o cualquier otro daño que surja o esté relacionado con el uso de esta Aplicación, incluido pero no limitado al consumo o manejo de cualquier sustancia identificada (correcta o incorrectamente) por la Aplicación.

4. Indemnización
Usted acepta indemnizar, defender y eximir de responsabilidad a los desarrolladores y propietarios de la Aplicación de cualquier reclamo, daño, pérdida, responsabilidad, costo y gasto (incluidos honorarios razonables de abogados) que surjan del uso de la Aplicación o del consumo o manejo de cualquier sustancia identificada por la Aplicación.

5. No es Consejo Médico o Profesional
La Aplicación no proporciona consejos médicos o nutricionales. Siempre consulte a expertos calificados antes de consumir plantas silvestres, hongos o cualquier artículo recolectado.

6. Requisito de Edad
Al usar esta Aplicación, usted declara que tiene al menos 18 años de edad o está usando la Aplicación bajo la supervisión de un padre o tutor legal que acepta estos Términos.

7. Aceptación
Al marcar la casilla y tocar "Continuar", usted reconoce que ha leído, comprendido y acepta estar sujeto a estos Términos de Servicio y Descargo de Responsabilidad.

Si no está de acuerdo, debe tocar "Rechazar" y desinstalar la aplicación.`,
  hi: `सेवा की शर्तें और अस्वीकरण
अंतिम अद्यतन: 28 नवंबर, 2025

[AlphaGo] ("ऐप") एक शैक्षिक और मनोरंजन उपकरण है जो कृत्रिम बुद्धिमत्ता द्वारा संचालित फोटोग्राफ विश्लेषण के माध्यम से उपभोग योग्य उत्पादों की पहचान करने में उपयोगकर्ताओं की सहायता के लिए डिज़ाइन किया गया है।

1. सटीकता की कोई गारंटी नहीं
ऐप द्वारा प्रदान की गई पहचान कृत्रिम बुद्धिमत्ता और तृतीय-पक्ष API द्वारा उत्पन्न की जाती है। ये पहचान 100% सटीक नहीं हैं और केवल सूचनात्मक और शैक्षिक उद्देश्यों के लिए प्रदान की जाती हैं। यह ऐप पेशेवर वनस्पति, कवक विज्ञान, चिकित्सा, या चारा विशेषज्ञता का विकल्प नहीं है।

2. जोखिम की धारणा
आप स्पष्ट रूप से स्वीकार करते हैं और सहमत हैं कि ऐप द्वारा प्रदान की गई जानकारी का कोई भी उपयोग, जिसमें ऐप द्वारा पहचाने गए किसी भी उपभोग योग्य उत्पाद या अन्य प्राकृतिक पदार्थ शामिल हैं, पूरी तरह से आपके अपने जोखिम पर किया जाता है।

3. नुकसान के लिए कोई दायित्व नहीं
किसी भी स्थिति में [AlphaGo] के डेवलपर्स, मालिक, सहयोगी, लाइसेंसकर्ता, या कोई संबंधित पक्ष इस ऐप के उपयोग से उत्पन्न या संबंधित किसी भी चोट, बीमारी, एलर्जी प्रतिक्रिया, विषाक्तता, मृत्यु, संपत्ति क्षति, या किसी अन्य नुकसान के लिए उत्तरदायी नहीं होंगे, जिसमें ऐप द्वारा पहचाने गए (सही या गलत) किसी भी पदार्थ की खपत या हैंडलिंग शामिल है लेकिन इन्हीं तक सीमित नहीं है।

4. क्षतिपूर्ति
आप ऐप के डेवलपर्स और मालिकों को किसी भी दावे, क्षति, हानि, देनदारी, लागत और खर्च (उचित वकील की फीस सहित) से क्षतिपूर्ति करने, बचाव करने और हानिरहित रखने के लिए सहमत हैं जो ऐप के आपके उपयोग या ऐप द्वारा पहचाने गए किसी भी पदार्थ की खपत या हैंडलिंग से उत्पन्न होते हैं।

5. चिकित्सा या पेशेवर सलाह नहीं
यह ऐप चिकित्सा या पोषण संबंधी सलाह प्रदान नहीं करता है। जंगली पौधों, मशरूम, या किसी भी चारा वस्तुओं का सेवन करने से पहले हमेशा योग्य विशेषज्ञों से परामर्श करें।

6. आयु आवश्यकता
इस ऐप का उपयोग करके आप प्रतिनिधित्व करते हैं कि आप कम से कम 18 वर्ष की आयु के हैं या इन शर्तों से सहमत माता-पिता या कानूनी अभिभावक की देखरेख में ऐप का उपयोग कर रहे हैं।

7. स्वीकृति
बॉक्स को चेक करके और "जारी रखें" पर टैप करके, आप स्वीकार करते हैं कि आपने इन सेवा की शर्तों और अस्वीकरण को पढ़ा, समझा और इनसे बाध्य होने के लिए सहमत हैं।

यदि आप सहमत नहीं हैं, तो आपको "अस्वीकार करें" पर टैप करना होगा और एप्लिकेशन को अनइंस्टॉल करना होगा।`,
  ar: `شروط الخدمة وإخلاء المسؤولية
آخر تحديث: 28 نوفمبر 2025

[AlphaGo] ("التطبيق") هو أداة تعليمية وترفيهية مصممة لمساعدة المستخدمين في تحديد المنتجات الاستهلاكية عبر تحليل الصور بواسطة الذكاء الاصطناعي.

1. عدم ضمان الدقة
التعريفات المقدمة من التطبيق يتم إنشاؤها بواسطة الذكاء الاصطناعي وواجهات برمجة التطبيقات الخارجية. هذه التعريفات ليست دقيقة بنسبة 100٪ ويتم توفيرها لأغراض إعلامية وتعليمية فقط. التطبيق ليس بديلاً عن الخبرة المهنية النباتية أو الفطرية أو الطبية أو خبرة البحث عن الطعام.

2. تحمل المخاطر
أنت تقر وتوافق صراحة على أن أي استخدام للمعلومات المقدمة من التطبيق، بما في ذلك على سبيل المثال لا الحصر أي منتج استهلاكي أو مادة طبيعية أخرى يحددها التطبيق، يتم على مسؤوليتك الخاصة بالكامل.

3. عدم المسؤولية عن الضرر
لن يكون المطورون أو المالكون أو الشركات التابعة أو المرخصون أو أي أطراف ذات صلة بـ [AlphaGo] مسؤولين بأي حال من الأحوال عن أي إصابة أو مرض أو رد فعل تحسسي أو تسمم أو وفاة أو ضرر بالممتلكات أو أي ضرر آخر ينشأ عن أو يتعلق باستخدام هذا التطبيق، بما في ذلك على سبيل المثال لا الحصر استهلاك أو التعامل مع أي مادة يحددها التطبيق (بشكل صحيح أو غير صحيح).

4. التعويض
أنت توافق على تعويض المطورين ومالكي التطبيق والدفاع عنهم وإبرائهم من أي مطالبات أو أضرار أو خسائر أو التزامات أو تكاليف ونفقات (بما في ذلك أتعاب المحاماة المعقولة) الناشئة عن استخدامك للتطبيق أو استهلاكك أو التعامل مع أي مادة يحددها التطبيق.

5. ليس نصيحة طبية أو مهنية
التطبيق لا يقدم نصائح طبية أو غذائية. استشر دائمًا الخبراء المؤهلين قبل استهلاك النباتات البرية أو الفطر أو أي عناصر يتم جمعها.

6. متطلبات العمر
باستخدام هذا التطبيق، فإنك تقر بأنك لا تقل عن 18 عامًا أو أنك تستخدم التطبيق تحت إشراف أحد الوالدين أو الوصي القانوني الذي يوافق على هذه الشروط.

7. القبول
بتحديد المربع والنقر على "متابعة"، فإنك تقر بأنك قرأت وفهمت ووافقت على الالتزام بشروط الخدمة وإخلاء المسؤولية هذه.

إذا كنت لا توافق، يجب عليك النقر على "رفض" وإلغاء تثبيت التطبيق.`,
  pt: `Termos de Serviço e Isenção de Responsabilidade
Última atualização: 28 de novembro de 2025

[AlphaGo] ("o Aplicativo") é uma ferramenta educacional e de entretenimento projetada para ajudar os usuários a identificar produtos consumíveis através de análise fotográfica impulsionada por inteligência artificial.

1. Sem Garantia de Precisão
As identificações fornecidas pelo Aplicativo são geradas por inteligência artificial e APIs de terceiros. Essas identificações NÃO são 100% precisas e são fornecidas apenas para fins informativos e educacionais. O Aplicativo NÃO é um substituto para experiência profissional botânica, micológica, médica ou de forrageamento.

2. Assunção de Risco
Você reconhece e concorda expressamente que qualquer uso das informações fornecidas pelo Aplicativo, incluindo mas não limitado a qualquer produto consumível ou outra substância natural identificada pelo Aplicativo, é feito inteiramente por sua própria conta e risco.

3. Sem Responsabilidade por Danos
Em nenhuma circunstância os desenvolvedores, proprietários, afiliados, licenciadores ou quaisquer partes relacionadas de [AlphaGo] serão responsáveis por qualquer lesão, doença, reação alérgica, envenenamento, morte, danos materiais ou qualquer outro dano decorrente ou relacionado ao uso deste Aplicativo, incluindo mas não limitado ao consumo ou manuseio de qualquer substância identificada (correta ou incorretamente) pelo Aplicativo.

4. Indenização
Você concorda em indenizar, defender e isentar os desenvolvedores e proprietários do Aplicativo de quaisquer reclamações, danos, perdas, responsabilidades, custos e despesas (incluindo honorários advocatícios razoáveis) decorrentes do seu uso do Aplicativo ou do seu consumo ou manuseio de qualquer substância identificada pelo Aplicativo.

5. Não é Conselho Médico ou Profissional
O Aplicativo não fornece conselhos médicos ou nutricionais. Sempre consulte especialistas qualificados antes de consumir plantas selvagens, cogumelos ou quaisquer itens coletados.

6. Requisito de Idade
Ao usar este Aplicativo, você declara que tem pelo menos 18 anos de idade ou está usando o Aplicativo sob a supervisão de um pai ou responsável legal que concorda com estes Termos.

7. Aceitação
Ao marcar a caixa e tocar em "Continuar", você reconhece que leu, compreendeu e concorda em estar vinculado a estes Termos de Serviço e Isenção de Responsabilidade.

Se você não concorda, deve tocar em "Recusar" e desinstalar o aplicativo.`,
  bn: `সেবার শর্তাবলী এবং দাবি পরিত্যাগ
সর্বশেষ আপডেট: ২৮ নভেম্বর, ২০২৫

[AlphaGo] ("অ্যাপ") একটি শিক্ষামূলক এবং বিনোদন সরঞ্জাম যা কৃত্রিম বুদ্ধিমত্তা দ্বারা চালিত ফটোগ্রাফ বিশ্লেষণের মাধ্যমে ব্যবহারকারীদের ভোগ্য পণ্য সনাক্ত করতে সহায়তা করার জন্য ডিজাইন করা হয়েছে।

১. নির্ভুলতার কোনো গ্যারান্টি নেই
অ্যাপ দ্বারা প্রদত্ত সনাক্তকরণ কৃত্রিম বুদ্ধিমত্তা এবং তৃতীয় পক্ষের API দ্বারা উত্পন্ন হয়। এই সনাক্তকরণগুলি ১০০% নির্ভুল নয় এবং শুধুমাত্র তথ্যমূলক এবং শিক্ষামূলক উদ্দেশ্যে প্রদান করা হয়। এই অ্যাপ পেশাদার উদ্ভিদবিদ্যা, ছত্রাকবিদ্যা, চিকিৎসা, বা খাদ্য সংগ্রহ দক্ষতার বিকল্প নয়।

২. ঝুঁকির অনুমান
আপনি স্পষ্টভাবে স্বীকার করেন এবং সম্মত হন যে অ্যাপ দ্বারা প্রদত্ত তথ্যের যেকোনো ব্যবহার, যার মধ্যে অ্যাপ দ্বারা চিহ্নিত যেকোনো ভোগ্য পণ্য বা অন্য প্রাকৃতিক পদার্থ অন্তর্ভুক্ত কিন্তু সীমাবদ্ধ নয়, সম্পূর্ণভাবে আপনার নিজের ঝুঁকিতে করা হয়।

৩. ক্ষতির জন্য কোনো দায় নেই
কোনো অবস্থাতেই [AlphaGo] এর ডেভেলপার, মালিক, সহযোগী, লাইসেন্সদাতা, বা কোনো সম্পর্কিত পক্ষ এই অ্যাপ ব্যবহার থেকে উদ্ভূত বা সম্পর্কিত যেকোনো আঘাত, অসুস্থতা, অ্যালার্জি প্রতিক্রিয়া, বিষক্রিয়া, মৃত্যু, সম্পত্তির ক্ষতি, বা অন্য যেকোনো ক্ষতির জন্য দায়ী থাকবে না, যার মধ্যে অ্যাপ দ্বারা চিহ্নিত (সঠিক বা ভুলভাবে) যেকোনো পদার্থের ব্যবহার বা হ্যান্ডলিং অন্তর্ভুক্ত কিন্তু সীমাবদ্ধ নয়।

৪. ক্ষতিপূরণ
আপনি অ্যাপের ডেভেলপার এবং মালিকদের যেকোনো দাবি, ক্ষতি, ক্ষতি, দায়, খরচ এবং ব্যয় (যুক্তিসঙ্গত আইনজীবী ফি সহ) থেকে ক্ষতিপূরণ, রক্ষা এবং ক্ষতিহীন রাখতে সম্মত হন যা অ্যাপের আপনার ব্যবহার বা অ্যাপ দ্বারা চিহ্নিত যেকোনো পদার্থের আপনার ব্যবহার বা হ্যান্ডলিং থেকে উদ্ভূত হয়।

৫. চিকিৎসা বা পেশাদার পরামর্শ নয়
অ্যাপ চিকিৎসা বা পুষ্টি পরামর্শ প্রদান করে না। বন্য উদ্ভিদ, মাশরুম, বা কোনো সংগৃহীত আইটেম খাওয়ার আগে সর্বদা যোগ্য বিশেষজ্ঞদের সাথে পরামর্শ করুন।

৬. বয়সের প্রয়োজনীয়তা
এই অ্যাপ ব্যবহার করে আপনি প্রতিনিধিত্ব করেন যে আপনার বয়স কমপক্ষে ১৮ বছর বা আপনি এই শর্তাবলীতে সম্মত পিতামাতা বা আইনি অভিভাবকের তত্ত্বাবধানে অ্যাপ ব্যবহার করছেন।

৭. গ্রহণযোগ্যতা
বক্সে চেক করে এবং "চালিয়ে যান" এ ট্যাপ করে, আপনি স্বীকার করেন যে আপনি এই সেবার শর্তাবলী এবং দাবি পরিত্যাগ পড়েছেন, বুঝেছেন এবং এর দ্বারা আবদ্ধ হতে সম্মত হয়েছেন।

আপনি যদি সম্মত না হন, তাহলে আপনাকে "প্রত্যাখ্যান করুন" এ ট্যাপ করতে হবে এবং অ্যাপ্লিকেশনটি আনইনস্টল করতে হবে।`,
  ru: `Условия обслуживания и отказ от ответственности
Последнее обновление: 28 ноября 2025 г.

[AlphaGo] («Приложение») — это образовательный и развлекательный инструмент, предназначенный для помощи пользователям в идентификации потребительских продуктов с помощью фотоанализа на основе искусственного интеллекта.

1. Без гарантии точности
Идентификации, предоставляемые Приложением, генерируются искусственным интеллектом и сторонними API. Эти идентификации НЕ являются на 100% точными и предоставляются только в информационных и образовательных целях. Приложение НЕ является заменой профессиональной ботанической, микологической, медицинской или фуражировочной экспертизы.

2. Принятие риска
Вы прямо признаете и соглашаетесь с тем, что любое использование информации, предоставленной Приложением, включая, но не ограничиваясь, любые потребительские продукты или другие природные вещества, идентифицированные Приложением, осуществляется полностью на ваш собственный риск.

3. Отсутствие ответственности за ущерб
Ни при каких обстоятельствах разработчики, владельцы, аффилированные лица, лицензиары или любые связанные стороны [AlphaGo] не несут ответственности за любые травмы, болезни, аллергические реакции, отравления, смерть, повреждение имущества или любой другой ущерб, возникающий в результате или связанный с использованием этого Приложения, включая, но не ограничиваясь, потребление или обращение с любым веществом, идентифицированным (правильно или неправильно) Приложением.

4. Возмещение убытков
Вы соглашаетесь возместить, защищать и освобождать от ответственности разработчиков и владельцев Приложения от любых претензий, убытков, потерь, обязательств, расходов и издержек (включая разумные гонорары адвокатов), возникающих в результате вашего использования Приложения или вашего потребления или обращения с любым веществом, идентифицированным Приложением.

5. Не является медицинской или профессиональной консультацией
Приложение не предоставляет медицинские или диетические консультации. Всегда консультируйтесь с квалифицированными специалистами перед употреблением диких растений, грибов или любых собранных предметов.

6. Возрастное требование
Используя это Приложение, вы заявляете, что вам не менее 18 лет или вы используете Приложение под наблюдением родителя или законного опекуна, который соглашается с этими Условиями.

7. Принятие
Установив флажок и нажав «Продолжить», вы подтверждаете, что прочитали, поняли и соглашаетесь соблюдать эти Условия обслуживания и отказ от ответственности.

Если вы не согласны, вы должны нажать «Отклонить» и удалить приложение.`,
};

export const TRANSLATIONS: Record<Language, {
  languageSelection: {
    title: string;
  };
  termsOfService: {
    title: string;
    agree: string;
    continue: string;
    decline: string;
    viewTerms: string;
  };
  cameraAccessRequired: string;
  cameraAccessDescription: string;
  grantPermission: string;
  scanInstruction: string;
  analyzingIngredients: string;
  settings: string;
  preferences: string;
  language: string;
  support: string;
  howToUse: string;
  howToUseDescription: string;
  betaProgram: string;
  betaProgramDescription: string;
  legal: string;
  termsOfServiceTitle: string;
  termsDescription: string;
  about: string;
  aboutDescription: string;
  settingsFooter: string;
}> = {
  en: {
    languageSelection: {
      title: "Select your language",
    },
    termsOfService: {
      title: "Terms of Service & Disclaimer",
      agree: "I have read and agree to the Terms of Service and Disclaimer",
      continue: "Continue",
      decline: "Decline",
      viewTerms: "Terms of Service & Disclaimer",
    },
    cameraAccessRequired: "Camera Access Required",
    cameraAccessDescription: "AlphaGo needs camera access to scan ingredient labels and help you stay safe.",
    grantPermission: "Grant Permission",
    scanInstruction: "Hold steady and tap to focus if needed",
    analyzingIngredients: "Analyzing ingredients...",
    settings: "Settings",
    preferences: "Preferences",
    language: "Language",
    support: "Support & Information",
    howToUse: "How to Use",
    howToUseDescription: "Learn how to scan items",
    betaProgram: "Beta Program",
    betaProgramDescription: "Early access & updates",
    legal: "Legal",
    termsOfServiceTitle: "Terms of Service",
    termsDescription: "View terms & disclaimer",
    about: "About AlphaGo",
    aboutDescription: "App version & information",
    settingsFooter: "AlphaGo - Allergen-Safe Scanning",
  },
  es: {
    languageSelection: {
      title: "Selecciona tu idioma",
    },
    termsOfService: {
      title: "Términos de Servicio y Descargo de Responsabilidad",
      agree: "He leído y acepto los Términos de Servicio y Descargo de Responsabilidad",
      continue: "Continuar",
      decline: "Rechazar",
      viewTerms: "Términos de Servicio y Descargo de Responsabilidad",
    },
    cameraAccessRequired: "Se requiere acceso a la cámara",
    cameraAccessDescription: "AlphaGo necesita acceso a la cámara para escanear etiquetas de ingredientes y ayudarte a mantenerte seguro.",
    grantPermission: "Conceder permiso",
    scanInstruction: "Mantén firme y toca para enfocar si es necesario",
    analyzingIngredients: "Analizando ingredientes...",
    settings: "Configuración",
    preferences: "Preferencias",
    language: "Idioma",
    support: "Soporte e Información",
    howToUse: "Cómo usar",
    howToUseDescription: "Aprende a escanear artículos",
    betaProgram: "Programa Beta",
    betaProgramDescription: "Acceso anticipado y actualizaciones",
    legal: "Legal",
    termsOfServiceTitle: "Términos de Servicio",
    termsDescription: "Ver términos y descargo de responsabilidad",
    about: "Acerca de AlphaGo",
    aboutDescription: "Versión de la aplicación e información",
    settingsFooter: "AlphaGo - Escaneo Seguro de Alérgenos",
  },
  hi: {
    languageSelection: {
      title: "अपनी भाषा चुनें",
    },
    termsOfService: {
      title: "सेवा की शर्तें और अस्वीकरण",
      agree: "मैंने सेवा की शर्तें और अस्वीकरण पढ़ लिया है और स्वीकार करता हूं",
      continue: "जारी रखें",
      decline: "अस्वीकार करें",
      viewTerms: "सेवा की शर्तें और अस्वीकरण",
    },
    cameraAccessRequired: "कैमरा एक्सेस आवश्यक है",
    cameraAccessDescription: "AlphaGo को सामग्री लेबल स्कैन करने और आपको सुरक्षित रखने में मदद करने के लिए कैमरा एक्सेस की आवश्यकता है।",
    grantPermission: "अनुमति दें",
    scanInstruction: "स्थिर रखें और आवश्यकता होने पर फोकस करने के लिए टैप करें",
    analyzingIngredients: "सामग्री का विश्लेषण कर रहे हैं...",
    settings: "सेटिंग्स",
    preferences: "वरीयताएँ",
    language: "भाषा",
    support: "समर्थन और जानकारी",
    howToUse: "कैसे उपयोग करें",
    howToUseDescription: "वस्तुओं को स्कैन करना सीखें",
    betaProgram: "बीटा कार्यक्रम",
    betaProgramDescription: "प्रारंभिक पहुंच और अपडेट",
    legal: "कानूनी",
    termsOfServiceTitle: "सेवा की शर्तें",
    termsDescription: "शर्तें और अस्वीकरण देखें",
    about: "AlphaGo के बारे में",
    aboutDescription: "ऐप संस्करण और जानकारी",
    settingsFooter: "AlphaGo - एलर्जेन-सुरक्षित स्कैनिंग",
  },
  ar: {
    languageSelection: {
      title: "اختر لغتك",
    },
    termsOfService: {
      title: "شروط الخدمة وإخلاء المسؤولية",
      agree: "لقد قرأت ووافقت على شروط الخدمة وإخلاء المسؤولية",
      continue: "متابعة",
      decline: "رفض",
      viewTerms: "شروط الخدمة وإخلاء المسؤولية",
    },
    cameraAccessRequired: "يتطلب الوصول إلى الكاميرا",
    cameraAccessDescription: "يحتاج AlphaGo إلى الوصول إلى الكاميرا لمسح ملصقات المكونات ومساعدتك على البقاء آمنًا.",
    grantPermission: "منح الإذن",
    scanInstruction: "امسك بثبات واضغط للتركيز إذا لزم الأمر",
    analyzingIngredients: "تحليل المكونات...",
    settings: "الإعدادات",
    preferences: "التفضيلات",
    language: "اللغة",
    support: "الدعم والمعلومات",
    howToUse: "كيفية الاستخدام",
    howToUseDescription: "تعلم كيفية مسح العناصر",
    betaProgram: "برنامج بيتا",
    betaProgramDescription: "الوصول المبكر والتحديثات",
    legal: "قانوني",
    termsOfServiceTitle: "شروط الخدمة",
    termsDescription: "عرض الشروط وإخلاء المسؤولية",
    about: "حول AlphaGo",
    aboutDescription: "إصدار التطبيق والمعلومات",
    settingsFooter: "AlphaGo - مسح آمن للحساسية",
  },
  pt: {
    languageSelection: {
      title: "Selecione seu idioma",
    },
    termsOfService: {
      title: "Termos de Serviço e Isenção de Responsabilidade",
      agree: "Li e concordo com os Termos de Serviço e Isenção de Responsabilidade",
      continue: "Continuar",
      decline: "Recusar",
      viewTerms: "Termos de Serviço e Isenção de Responsabilidade",
    },
    cameraAccessRequired: "Acesso à câmera necessário",
    cameraAccessDescription: "AlphaGo precisa de acesso à câmera para escanear rótulos de ingredientes e ajudá-lo a ficar seguro.",
    grantPermission: "Conceder permissão",
    scanInstruction: "Segure firme e toque para focar se necessário",
    analyzingIngredients: "Analisando ingredientes...",
    settings: "Configurações",
    preferences: "Preferências",
    language: "Idioma",
    support: "Suporte e Informações",
    howToUse: "Como Usar",
    howToUseDescription: "Aprenda a escanear itens",
    betaProgram: "Programa Beta",
    betaProgramDescription: "Acesso antecipado e atualizações",
    legal: "Legal",
    termsOfServiceTitle: "Termos de Serviço",
    termsDescription: "Ver termos e isenção de responsabilidade",
    about: "Sobre AlphaGo",
    aboutDescription: "Versão do aplicativo e informações",
    settingsFooter: "AlphaGo - Escaneamento Seguro de Alérgenos",
  },
  bn: {
    languageSelection: {
      title: "আপনার ভাষা নির্বাচন করুন",
    },
    termsOfService: {
      title: "সেবার শর্তাবলী এবং দাবি পরিত্যাগ",
      agree: "আমি সেবার শর্তাবলী এবং দাবি পরিত্যাগ পড়েছি এবং সম্মত হয়েছি",
      continue: "চালিয়ে যান",
      decline: "প্রত্যাখ্যান করুন",
      viewTerms: "সেবার শর্তাবলী এবং দাবি পরিত্যাগ",
    },
    cameraAccessRequired: "ক্যামেরা অ্যাক্সেস প্রয়োজন",
    cameraAccessDescription: "AlphaGo-কে উপাদান লেবেল স্কান করতে এবং আপনাকে নিরাপদ থাকতে সাহায্য করতে ক্যামেরা অ্যাক্সেস প্রয়োজন।",
    grantPermission: "অনুমতি দিন",
    scanInstruction: "স্থির রাখুন এবং প্রয়োজন হলে ফোকাস করতে ট্যাপ করুন",
    analyzingIngredients: "উপাদান বিশ্লেষণ করা হচ্ছে...",
    settings: "সেটিংস",
    preferences: "পছন্দসমূহ",
    language: "ভাষা",
    support: "সমর্থন এবং তথ্য",
    howToUse: "কীভাবে ব্যবহার করবেন",
    howToUseDescription: "আইটেম স্কান করতে শিখুন",
    betaProgram: "বিটা প্রোগ্রাম",
    betaProgramDescription: "প্রাথমিক অ্যাক্সেস এবং আপডেট",
    legal: "আইনি",
    termsOfServiceTitle: "সেবার শর্তাবলী",
    termsDescription: "শর্তাবলী এবং দাবি পরিত্যাগ দেখুন",
    about: "AlphaGo সম্পর্কে",
    aboutDescription: "অ্যাপ সংস্করণ এবং তথ্য",
    settingsFooter: "AlphaGo - এলার্জেন-নিরাপদ স্ক্যানিং",
  },
  ru: {
    languageSelection: {
      title: "Выберите ваш язык",
    },
    termsOfService: {
      title: "Условия обслуживания и отказ от ответственности",
      agree: "Я прочитал и согласен с Условиями обслуживания и отказом от ответственности",
      continue: "Продолжить",
      decline: "Отклонить",
      viewTerms: "Условия обслуживания и отказ от ответственности",
    },
    cameraAccessRequired: "Требуется доступ к камере",
    cameraAccessDescription: "AlphaGo нужен доступ к камере для сканирования этикеток ингредиентов и помощи в безопасности.",
    grantPermission: "Предоставить разрешение",
    scanInstruction: "Держите крепко и коснитесь для фокусировки при необходимости",
    analyzingIngredients: "Анализ ингредиентов...",
    settings: "Настройки",
    preferences: "Предпочтения",
    language: "Язык",
    support: "Поддержка и информация",
    howToUse: "Как использовать",
    howToUseDescription: "Узнайте, как сканировать товары",
    betaProgram: "Бета-программа",
    betaProgramDescription: "Ранний доступ и обновления",
    legal: "Юридическая информация",
    termsOfServiceTitle: "Условия обслуживания",
    termsDescription: "Просмотр условий и отказ от ответственности",
    about: "О AlphaGo",
    aboutDescription: "Версия приложения и информация",
    settingsFooter: "AlphaGo - Безопасное сканирование аллергенов",
  },
};
